export const STANDARD_LABELS = [
  'Kwa Mashu To The World',
  'Umlazi Ailwo!',
  'SA Flag Barcode',
  'Izinto Zothando',
  'Made In The Township',
  'Crazy Button Mascot',
  'No Haters Club',
  'Eish!',
  'Grootman Approved',
  'Drip Built Different',
  'Pushin’ Kasi Dreams',
  'Braam Certified',
];

export const DEFAULT_CATEGORIES = [
  'Spaza Drip',
  'Braam Flex',
  'Kasi Heat',
  'Mzansi Mosaic',
  'Zulu Future',
  'Ekasi Royalty',
  'Thrift Flex',
  'No Haters Club',
  'Braam Nights',
  'Mama Said',
];

export const BRAND_STORY = {
  tagline: 'Wear Loud. Walk Proud.',
  voice: 'Loud, playful, unapologetic, authentic.',
  usp: 'Mzansi’s Loudest Streetwear – designed in our townships, rocked worldwide.',
  palette: 'South African flag spectrum • Green • Gold • Black • Red • Blue • White',
  audience: 'Township trendsetters, skaters, dancers, and street creators aged 16–28.',
  contact: {
    owner: 'Mr Edgar Rudolph Tshatshu',
    phone: '+41 76 25 23 825',
    email: 'edgar.tshatshu@icloud.com',
    instagram: 'https://www.instagram.com/crazybuttonsa/',
  },
};

export const TAGLINE_OPTIONS = [
  'Wear Loud. Walk Proud.',
  'For the Brave. From the Block.',
  'Mzansi Made, Globally Played.',
  'No Chill, All Drip.',
  'Culture in Every Stitch.',
];

export const AUDIENCE_PERSONAS = [
  {
    name: 'The Skater-Creator',
    description: 'Cape Town or Jozi creative filming edits for TikTok/IG who needs durable pieces that still slap online.',
  },
  {
    name: 'The Street Dancer',
    description: 'Pantsula + amapiano movers looking for gear that breathes, stretches, and pops under stage lights.',
  },
  {
    name: 'The Township Trendsetter',
    description: 'First to rock new drops, spreads hype through the hood, and uses fashion to rep their story.',
  },
];

export const PATCH_DROP = [
  { title: 'Kwa Mashu To The World', description: 'Bold banner vibes. From eKasi to global, rep your roots loud.' },
  { title: 'Umlazi Ailwo!', description: 'Jagged and loud like a bassline in a taxi — if you know, you know.' },
  { title: 'SA Flag Barcode', description: 'Flag drip meets street tech. Scan the vibe, feel the culture.' },
  { title: 'Izinto Zothando', description: 'Broken heart stitched with love. Gogo meets Kota — this one’s personal.' },
  { title: 'Made In The Township', description: 'Stamped with pride. Tough thread, tougher history. Authenticity isn’t optional.' },
  { title: 'Crazy Button Mascot', description: 'Gold tooth, sneakers, mad attitude. The brand got a face now.' },
  { title: 'No Haters Club', description: 'Varsity block with peaceful fists. Exclusive zone only — haters left at the gate.' },
  { title: 'Eish!', description: 'Speech bubble drip. You can hear this one — slang that speaks for itself.' },
  { title: 'Grootman Approved', description: 'For the OGs and day ones. Fedora + cane energy, certified wisdom.' },
  { title: 'Drip Built Different', description: 'Brick by brick. Streetwear made for pressure — kasi-built, never copied.' },
  { title: 'Pushin’ Kasi Dreams', description: 'Skater meets taxi hustle. Straight out the township grind.' },
  { title: 'Braam Certified', description: 'Neon triangle. Streetlight. Shades. Nightlife stitched in thread.' },
];

export const PRODUCT_TEMPLATES = [
  {
    id: 'zulu-future-tech-jacket',
    title: '“Zulu Future” Tech Jacket',
    subtitle: 'Relaxed tailoring + bold outerwear',
    description: 'Waterproof nylon bomber with mesh lining, transparent zip panels, and bead-inspired accents.',
    category: 'Zulu Future',
    labels: ['Kwa Mashu To The World', 'SA Flag Barcode'],
    priceZAR: 1899,
    priceEUR: 95,
    tags: ['Techwear', 'Outerwear', 'Kwa Mashu'],
    webUrl: 'https://crazybuttonsa.com/products/zulu-future-tech-jacket',
    status: 'draft',
  },
  {
    id: 'ekasi-royalty-denim',
    title: '“Ekasi Royalty” Denim Set',
    subtitle: 'Vintage Americana x township drip',
    description: 'Oversized denim jacket + relaxed jeans with township graffiti art and detachable patch.',
    category: 'Ekasi Royalty',
    labels: ['Made In The Township', 'Braam Certified'],
    priceZAR: 2199,
    priceEUR: 110,
    tags: ['Denim', 'Set', 'Graffiti'],
    webUrl: 'https://crazybuttonsa.com/products/ekasi-royalty-denim-set',
    status: 'draft',
  },
  {
    id: 'thrift-flex-cardigan',
    title: '“Thrift Flex” Grandpa Cardigan',
    subtitle: 'Eclectic grandpa meets streetwear',
    description: 'Nguni woven patterns, recycled wool, gold Crazy Button badge, “Yizwa ke manje” lining.',
    category: 'Thrift Flex',
    labels: ['Grootman Approved', 'Izinto Zothando'],
    priceZAR: 1599,
    priceEUR: 80,
    tags: ['Knitwear', 'Nguni', 'Recycled'],
    webUrl: 'https://crazybuttonsa.com/products/thrift-flex-cardigan',
    status: 'draft',
  },
  {
    id: 'no-haters-rugby',
    title: '“No Haters Club” Rugby Tee',
    subtitle: 'Elevated athleisure with township pride',
    description: 'Collared 90s rugby top, color-blocked flag pattern, sleeve patch + Umlazi coordinates.',
    category: 'No Haters Club',
    labels: ['No Haters Club', 'Eish!'],
    priceZAR: 1299,
    priceEUR: 65,
    tags: ['Rugby', 'Athleisure', 'Umlazi'],
    webUrl: 'https://crazybuttonsa.com/products/no-haters-club-rugby',
    status: 'draft',
  },
  {
    id: 'braam-nights-track',
    title: '“Braam Nights” Wide-Leg Track Pants',
    subtitle: 'Modern streetwear x relaxed tailoring',
    description: 'Midnight blue nylon-silk blend with green/red side-stripe and hidden mantra “We move different.”',
    category: 'Braam Nights',
    labels: ['Drip Built Different', 'Pushin’ Kasi Dreams'],
    priceZAR: 1499,
    priceEUR: 75,
    tags: ['Track', 'Nylon', 'Hidden Message'],
    webUrl: 'https://crazybuttonsa.com/products/braam-nights-track-pants',
    status: 'draft',
  },
  {
    id: 'mama-said-tee',
    title: '“Mama Said” Graphic Tee',
    subtitle: 'Sustainable streetwear storytelling',
    description: 'Cream oversized tee with vintage gogo portrait and “Wear Something Warm” caption.',
    category: 'Mama Said',
    labels: ['Izinto Zothando', 'Made In The Township'],
    priceZAR: 899,
    priceEUR: 45,
    tags: ['Graphic Tee', 'Sustainable', 'Storytelling'],
    webUrl: 'https://crazybuttonsa.com/products/mama-said-graphic-tee',
    status: 'draft',
  },
];
